# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded   rattleCAD  3.4 "\ 
        [list source  [file join $dir lib__model.tcl]]; \
        [list source  [file join $dir lib__control.tcl]]; \
        [list source  [file join $dir lib__view.tcl]]; \
        [list source  [file join $dir lib_file.tcl]]; \
        [list source  [file join $dir lib_gui.tcl]]; \
        [list source  [file join $dir lib_cfgReport.tcl]]; \
        [list source  [file join $dir lib_config.tcl]]; \
        [list source  [file join $dir lib_compLibrary.tcl]]; \
        [list source  [file join $dir lib_bikeRendering.tcl]]; \
        [list source  [file join $dir lib_version_info.tcl]]; \
        [list source  [file join $dir lib_projectUpdate.tcl]]; \
        [list source  [file join $dir lib_cvCustom.tcl]]; \
        [list source  [file join $dir lib_cvRearMockup.tcl]]; \
        [list source  [file join $dir lib_cvFrameJig.tcl]]; \
        [list source  [file join $dir lib_cvUpdate.tcl]]; \
        [list source  [file join $dir lib_test.tcl]]; \
        [list source  [file join $dir lib_debug.tcl]]; \
        [list source  [file join $dir lib_tool.tcl]]; \
        [list source  [file join $dir rattleCAD.tcl]]; \ 
   "

 # .. unused since 3.1.00
 # [list source  [file join $dir lib_control.tcl]]; 
 # [list source  [file join $dir lib_frame_ref_geometry.tcl]]; \        
