# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded   rattle_cad  2.8 "\
        package require    AppUtil     0.8; \
        [list source  [file join $dir rattle_cad.tcl]]; \
        [list source  [file join $dir lib_config.tcl]]; \
        [list source  [file join $dir lib_control.tcl]]; \
        [list source  [file join $dir lib_canvas.tcl]]; \
        [list source  [file join $dir lib_cv_design.tcl]]; \
        [list source  [file join $dir lib_cv_detail.tcl]]; \
        [list source  [file join $dir lib_cv_drafting.tcl]]; \
        [list source  [file join $dir lib_geometry.tcl]]; \
        [list source  [file join $dir lib_geometry_2x.tcl]]; \
        [list source  [file join $dir lib_mathematic.tcl]]; \
        [list source  [file join $dir lib_version_info.tcl]]; \
        [list source  [file join $dir lib_tubemiter.tcl]]; \
    "

